# Generated by Django 5.2.4 on 2025-07-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NERPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sms_inquiry_id", models.IntegerField()),
                ("model_version", models.CharField(max_length=16)),
                ("extracted_entities", models.JSONField()),
                ("response_time_ms", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
