# Generated by Django 5.2.4 on 2025-07-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0002_rename_nerprediction_entityprediction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entityprediction",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="entityprediction",
            old_name="sms_inquiry_id",
            new_name="sms_id",
        ),
    ]
