# Generated by Django 5.2.4 on 2025-07-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0003_rename_created_at_entityprediction_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityprediction",
            name="model_name",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
