# Generated by Django 5.2.4 on 2025-07-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0004_entityprediction_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityprediction",
            name="model_name",
            field=models.CharField(
                choices=[("en_streetninja", "En Streetninja")], max_length=256
            ),
        ),
    ]
