# Generated by Django 5.2.4 on 2025-07-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0006_remove_entityprediction_model_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("en_streetninja", "En Streetninja")],
                        max_length=256,
                        unique=True,
                    ),
                ),
                ("version", models.CharField(max_length=24)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"), name="unique_model_version"
                    )
                ],
            },
        ),
    ]
