# Generated by Django 5.2.4 on 2025-07-29 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0007_mlmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityprediction",
            name="ml_model",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictions",
                to="nlp.mlmodel",
            ),
            preserve_default=False,
        ),
    ]
